// Generated by CoffeeScript 1.5.0
/*
  http://github.com/paulyoung/require-cson
*/

define(['coffee-script', 'text'], function(CoffeeScript, text) {
  var buildMap;
  buildMap = {};
  return {
    load: function(name, req, onLoad, config) {
      if (config.isBuild) {
        text.get(req.toUrl("" + name + ".cson"), function(data) {
          try {
            data = JSON.stringify(CoffeeScript["eval"](data, {
              bare: true,
              sandbox: true
            }));
          } catch (err) {
            throw err;
          }
          return buildMap[name] = data;
        });
      }
      return onLoad(null);
    },
    write: function(pluginName, moduleName, write) {
      if (moduleName in buildMap) {
        return write("define(\"" + pluginName + "!" + moduleName + "\", function() {\n  return " + buildMap[moduleName] + ";\n});\n");
      }
    }
  };
});
